import Head from "next/head";
import { useState, useEffect } from "react";
import Image from "next/image";
import BlackHole1 from "../../public/iconW.png";
import Cover from "../../public/Purple.jpg";
import CoverVert from "../../public/purpleVert.jpg";
import Nav from "./Nav";
import TextField from "./TextField";
import Banner from "./Banner";
// import styles from '@/styles/Home.module.css'

export default function Home() {
  // Background-Changer
  const [imageUrl, setImageUrl] = useState(Cover);

  useEffect(() => {
    const handleResize = () => {
      const newImageUrl = window.innerWidth >= 768 ? Cover : CoverVert;
      setImageUrl(newImageUrl);
    };

    window.addEventListener("resize", handleResize);
    handleResize();

    return () => window.removeEventListener("resize", handleResize);
  }, []);

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Background Image */}
      <div
        style={{
          zIndex: -100,
          position: "fixed",
        }}
      >
        <Image
          className=""
          src={imageUrl}
          alt="black hole"
          // fill
          // objectFit="cover"
        />
      </div>

      {/* Body Start */}
      <div className="relative FlexCenterCol font-pop border-sky-900 h-screen">
        {/* <Banner /> */}
        <div className="w-screen h-12  border-b-sky-"></div>
        {/* Flex Canvas Start */}
        <div className="FlexCenterCol md:flex-row p-4 IceGrade BoxFull ">
          {/* Intro Card */}
          <div className="CardMD p-4 flex flex-col md:mr-6 Hover Glass h-fit w-full md:w-1/4 md:h-full md:flex-2 ">
            {/* Card Header */}
            <div className="w-full items-center h-fit flex justify-between">
              <h1 className="font- NameShadow text-4xl md:text-5xl font-bold text-left">
                Black Holes
              </h1>
              <div className="text-white mx-4 BoxFit">
                <Image className="text-center Spin" src={BlackHole1} alt="#" />
              </div>
            </div>

            {/* First Text Box */}
            {/* <div className="NameShadow bg-coal FlexCenter text-md Round text-left Glass "> */}
            <p className="p-4 leading-6 text-sm">
              I've been thinking black holes represent a 'turn-over point' where
              'information from this simulation i.e. galaxy is compressed back
              into light and siphoned into an underlying matrix (beyond our
              human detection) to help iterate the next
              simulation/galaxy/universe. The basis of this being that evolution
              appears to be a constant and the universe is constantly learning
              from itself.
            </p>

            {/* </div> */}
          </div>

          {/* Column 2 */}
          <div className="MARK -z-20 -mt-12 mb-24  flex-1 FlexCenterCol p-8  Round h-full w-full md:w-4/6">
            {/* Main Dash */}
            {/* Dash Top Canvas */}
            <div className="FlexCenter MARK p-4 h-1/2 w-full">
              <div className="MARK DashTop bg-slate-300">
                <Image
                  className="Round"
                  src={Cover}
                  alt="black hole"
                  fill
                  objectFit="cover"
                />
              </div>
            </div>

            {/* Dash Box Canvas */}
            <div className="MARK  gap-8 p-4 BoxFull border-violet-400"></div>
            {/* </div> */}
          </div>
        </div>

        {/* Text Field */}
        <TextField />
        <div className="absolute bottom-0">
          <Nav />
        </div>
      </div>
    </div>
  );
}
